// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bridge/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgBridgeERC20FromEthereum defines a ERC20 bridge transfer from Ethereum.
type MsgBridgeERC20FromEthereum struct {
	Relayer string `protobuf:"bytes,1,opt,name=relayer,proto3" json:"relayer,omitempty"`
	// Originating Ethereum ERC20 contract address
	EthereumERC20Address string `protobuf:"bytes,2,opt,name=ethereum_erc20_address,json=ethereumErc20Address,proto3" json:"ethereum_erc20_address,omitempty"`
	// ERC20 token amount to transfer
	Amount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
	// Receiver hex address on Kava
	Receiver string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// Unique sequence per bridge event
	Sequence github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=sequence,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"sequence"`
}

func (m *MsgBridgeERC20FromEthereum) Reset()         { *m = MsgBridgeERC20FromEthereum{} }
func (m *MsgBridgeERC20FromEthereum) String() string { return proto.CompactTextString(m) }
func (*MsgBridgeERC20FromEthereum) ProtoMessage()    {}
func (*MsgBridgeERC20FromEthereum) Descriptor() ([]byte, []int) {
	return fileDescriptor_e83acf120314329f, []int{0}
}
func (m *MsgBridgeERC20FromEthereum) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBridgeERC20FromEthereum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBridgeERC20FromEthereum.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBridgeERC20FromEthereum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBridgeERC20FromEthereum.Merge(m, src)
}
func (m *MsgBridgeERC20FromEthereum) XXX_Size() int {
	return m.Size()
}
func (m *MsgBridgeERC20FromEthereum) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBridgeERC20FromEthereum.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBridgeERC20FromEthereum proto.InternalMessageInfo

func (m *MsgBridgeERC20FromEthereum) GetRelayer() string {
	if m != nil {
		return m.Relayer
	}
	return ""
}

func (m *MsgBridgeERC20FromEthereum) GetEthereumERC20Address() string {
	if m != nil {
		return m.EthereumERC20Address
	}
	return ""
}

func (m *MsgBridgeERC20FromEthereum) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

// MsgBridgeERC20FromEthereumResponse defines the response value from
type MsgBridgeERC20FromEthereumResponse struct {
}

func (m *MsgBridgeERC20FromEthereumResponse) Reset()         { *m = MsgBridgeERC20FromEthereumResponse{} }
func (m *MsgBridgeERC20FromEthereumResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBridgeERC20FromEthereumResponse) ProtoMessage()    {}
func (*MsgBridgeERC20FromEthereumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e83acf120314329f, []int{1}
}
func (m *MsgBridgeERC20FromEthereumResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBridgeERC20FromEthereumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBridgeERC20FromEthereumResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBridgeERC20FromEthereumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBridgeERC20FromEthereumResponse.Merge(m, src)
}
func (m *MsgBridgeERC20FromEthereumResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBridgeERC20FromEthereumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBridgeERC20FromEthereumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBridgeERC20FromEthereumResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgBridgeERC20FromEthereum)(nil), "bridge.v1beta1.MsgBridgeERC20FromEthereum")
	proto.RegisterType((*MsgBridgeERC20FromEthereumResponse)(nil), "bridge.v1beta1.MsgBridgeERC20FromEthereumResponse")
}

func init() { proto.RegisterFile("bridge/v1beta1/tx.proto", fileDescriptor_e83acf120314329f) }

var fileDescriptor_e83acf120314329f = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x3f, 0x0f, 0xd2, 0x40,
	0x18, 0xc6, 0x7b, 0xa0, 0x88, 0x37, 0x38, 0x34, 0x8d, 0xd4, 0x0e, 0x87, 0x21, 0xc6, 0x18, 0x93,
	0xb6, 0x50, 0x57, 0x17, 0x31, 0x98, 0x30, 0x60, 0x62, 0x75, 0x30, 0x2e, 0xa4, 0x7f, 0xde, 0x94,
	0x06, 0xda, 0xc3, 0xbb, 0x2b, 0x81, 0xcd, 0x8f, 0xe0, 0xc7, 0xf0, 0x03, 0xf0, 0x21, 0x18, 0x09,
	0x93, 0x71, 0x20, 0x58, 0x56, 0x3f, 0x84, 0xa1, 0x77, 0x25, 0x3a, 0x90, 0x38, 0x38, 0xf5, 0xbd,
	0x3e, 0xcf, 0xf3, 0x7b, 0xef, 0xde, 0x3b, 0xdc, 0x09, 0x59, 0x1a, 0x27, 0xe0, 0xae, 0x06, 0x21,
	0x88, 0x60, 0xe0, 0x8a, 0xb5, 0xb3, 0x64, 0x54, 0x50, 0xfd, 0x81, 0x14, 0x1c, 0x25, 0x58, 0x46,
	0x42, 0x13, 0x5a, 0x49, 0xee, 0xa5, 0x92, 0x2e, 0xeb, 0x51, 0x44, 0x79, 0x46, 0xf9, 0x54, 0x0a,
	0x72, 0x21, 0xa5, 0xde, 0xaf, 0x06, 0xb6, 0x26, 0x3c, 0x19, 0x56, 0x98, 0x91, 0xff, 0xda, 0xeb,
	0xbf, 0x61, 0x34, 0x1b, 0x89, 0x19, 0x30, 0x28, 0x32, 0xdd, 0xc3, 0xf7, 0x18, 0x2c, 0x82, 0x0d,
	0x30, 0x13, 0x3d, 0x46, 0xcf, 0xee, 0x0f, 0xcd, 0xc3, 0xd6, 0x36, 0x14, 0xe1, 0x55, 0x1c, 0x33,
	0xe0, 0xfc, 0xbd, 0x60, 0x69, 0x9e, 0xf8, 0xb5, 0x51, 0x7f, 0x8b, 0x1f, 0x82, 0xca, 0x4f, 0x81,
	0x45, 0x5e, 0x7f, 0x1a, 0x48, 0xa3, 0xd9, 0x90, 0x88, 0xf2, 0xd8, 0x35, 0xea, 0x0e, 0x55, 0x4b,
	0x05, 0xf2, 0x8d, 0x3a, 0x37, 0xba, 0xc4, 0xd4, 0x5f, 0xfd, 0x03, 0x6e, 0x05, 0x19, 0x2d, 0x72,
	0x61, 0x36, 0xab, 0xfc, 0xcb, 0xdd, 0xb1, 0xab, 0xfd, 0x38, 0x76, 0x9f, 0x26, 0xa9, 0x98, 0x15,
	0xa1, 0x13, 0xd1, 0x4c, 0x9d, 0x49, 0x7d, 0x6c, 0x1e, 0xcf, 0x5d, 0xb1, 0x59, 0x02, 0x77, 0xc6,
	0xb9, 0x38, 0x6c, 0x6d, 0xac, 0x36, 0x3c, 0xce, 0x85, 0xaf, 0x58, 0xba, 0x85, 0xdb, 0x0c, 0x22,
	0x48, 0x57, 0xc0, 0xcc, 0x3b, 0x17, 0xae, 0x7f, 0x5d, 0xeb, 0x1f, 0x71, 0x9b, 0xc3, 0xe7, 0x02,
	0xf2, 0x08, 0xcc, 0xbb, 0xff, 0xa1, 0xe7, 0x95, 0xd6, 0x7b, 0x82, 0x7b, 0xb7, 0xa7, 0xed, 0x03,
	0x5f, 0xd2, 0x9c, 0x83, 0xf7, 0x05, 0xe1, 0xe6, 0x84, 0x27, 0xfa, 0x06, 0x77, 0x6e, 0x5d, 0xcc,
	0x73, 0xe7, 0xef, 0x9b, 0x77, 0x6e, 0x63, 0x2d, 0xef, 0xdf, 0xbd, 0xf5, 0x16, 0x86, 0xef, 0x4e,
	0x3f, 0x09, 0xfa, 0x56, 0x12, 0xb4, 0x2b, 0x09, 0xda, 0x97, 0x04, 0x9d, 0x4a, 0x82, 0xbe, 0x9e,
	0x89, 0xb6, 0x3f, 0x13, 0xed, 0xfb, 0x99, 0x68, 0x9f, 0xdc, 0x3f, 0x46, 0x31, 0x0f, 0x56, 0x81,
	0xbd, 0x08, 0x42, 0x2e, 0x2b, 0xf5, 0x5a, 0xd7, 0xae, 0x2a, 0xaa, 0xb9, 0x84, 0xad, 0xea, 0xc5,
	0xbd, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xe1, 0xaa, 0xb7, 0xcd, 0x02, 0x00, 0x00,
}

func (this *MsgBridgeERC20FromEthereum) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*MsgBridgeERC20FromEthereum)
	if !ok {
		that2, ok := that.(MsgBridgeERC20FromEthereum)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *MsgBridgeERC20FromEthereum")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *MsgBridgeERC20FromEthereum but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *MsgBridgeERC20FromEthereum but is not nil && this == nil")
	}
	if this.Relayer != that1.Relayer {
		return fmt.Errorf("Relayer this(%v) Not Equal that(%v)", this.Relayer, that1.Relayer)
	}
	if this.EthereumERC20Address != that1.EthereumERC20Address {
		return fmt.Errorf("EthereumERC20Address this(%v) Not Equal that(%v)", this.EthereumERC20Address, that1.EthereumERC20Address)
	}
	if !this.Amount.Equal(that1.Amount) {
		return fmt.Errorf("Amount this(%v) Not Equal that(%v)", this.Amount, that1.Amount)
	}
	if this.Receiver != that1.Receiver {
		return fmt.Errorf("Receiver this(%v) Not Equal that(%v)", this.Receiver, that1.Receiver)
	}
	if !this.Sequence.Equal(that1.Sequence) {
		return fmt.Errorf("Sequence this(%v) Not Equal that(%v)", this.Sequence, that1.Sequence)
	}
	return nil
}
func (this *MsgBridgeERC20FromEthereum) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgBridgeERC20FromEthereum)
	if !ok {
		that2, ok := that.(MsgBridgeERC20FromEthereum)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Relayer != that1.Relayer {
		return false
	}
	if this.EthereumERC20Address != that1.EthereumERC20Address {
		return false
	}
	if !this.Amount.Equal(that1.Amount) {
		return false
	}
	if this.Receiver != that1.Receiver {
		return false
	}
	if !this.Sequence.Equal(that1.Sequence) {
		return false
	}
	return true
}
func (this *MsgBridgeERC20FromEthereumResponse) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*MsgBridgeERC20FromEthereumResponse)
	if !ok {
		that2, ok := that.(MsgBridgeERC20FromEthereumResponse)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *MsgBridgeERC20FromEthereumResponse")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *MsgBridgeERC20FromEthereumResponse but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *MsgBridgeERC20FromEthereumResponse but is not nil && this == nil")
	}
	return nil
}
func (this *MsgBridgeERC20FromEthereumResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgBridgeERC20FromEthereumResponse)
	if !ok {
		that2, ok := that.(MsgBridgeERC20FromEthereumResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// BridgeERC20FromEthereum defines a method for bridging ERC20 tokens from
	// Ethereum.
	BridgeERC20FromEthereum(ctx context.Context, in *MsgBridgeERC20FromEthereum, opts ...grpc.CallOption) (*MsgBridgeERC20FromEthereumResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) BridgeERC20FromEthereum(ctx context.Context, in *MsgBridgeERC20FromEthereum, opts ...grpc.CallOption) (*MsgBridgeERC20FromEthereumResponse, error) {
	out := new(MsgBridgeERC20FromEthereumResponse)
	err := c.cc.Invoke(ctx, "/bridge.v1beta1.Msg/BridgeERC20FromEthereum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// BridgeERC20FromEthereum defines a method for bridging ERC20 tokens from
	// Ethereum.
	BridgeERC20FromEthereum(context.Context, *MsgBridgeERC20FromEthereum) (*MsgBridgeERC20FromEthereumResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) BridgeERC20FromEthereum(ctx context.Context, req *MsgBridgeERC20FromEthereum) (*MsgBridgeERC20FromEthereumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeERC20FromEthereum not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_BridgeERC20FromEthereum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBridgeERC20FromEthereum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BridgeERC20FromEthereum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bridge.v1beta1.Msg/BridgeERC20FromEthereum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BridgeERC20FromEthereum(ctx, req.(*MsgBridgeERC20FromEthereum))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BridgeERC20FromEthereum",
			Handler:    _Msg_BridgeERC20FromEthereum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge/v1beta1/tx.proto",
}

func (m *MsgBridgeERC20FromEthereum) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBridgeERC20FromEthereum) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBridgeERC20FromEthereum) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Sequence.Size()
		i -= size
		if _, err := m.Sequence.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.EthereumERC20Address) > 0 {
		i -= len(m.EthereumERC20Address)
		copy(dAtA[i:], m.EthereumERC20Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EthereumERC20Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Relayer) > 0 {
		i -= len(m.Relayer)
		copy(dAtA[i:], m.Relayer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Relayer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBridgeERC20FromEthereumResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBridgeERC20FromEthereumResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBridgeERC20FromEthereumResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgBridgeERC20FromEthereum) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Relayer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EthereumERC20Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Sequence.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgBridgeERC20FromEthereumResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgBridgeERC20FromEthereum) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBridgeERC20FromEthereum: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBridgeERC20FromEthereum: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relayer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relayer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthereumERC20Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthereumERC20Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sequence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBridgeERC20FromEthereumResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBridgeERC20FromEthereumResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBridgeERC20FromEthereumResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
