// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/v1beta1/broadcast_message.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	github_com_libp2p_go_libp2p_core_peer "github.com/libp2p/go-libp2p-core/peer"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BroadcastMessage is used between peers to wrap messages for each protocol
type BroadcastMessage struct {
	// Unique ID of this message.
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Selected recipients of the message, to partially restrict the broadcast to
	// a subset a peers.
	RecipientPeerIDs []github_com_libp2p_go_libp2p_core_peer.ID `protobuf:"bytes,2,rep,name=recipient_peer_ids,json=recipientPeerIds,proto3,customtype=github.com/libp2p/go-libp2p-core/peer.ID" json:"recipient_peer_ids,omitempty"`
	// Customtype workaround for not having to use a separate protocgen.sh script
	Payload github_com_gogo_protobuf_types.Any `protobuf:"bytes,3,opt,name=payload,proto3,customtype=github.com/gogo/protobuf/types.Any" json:"payload"`
	// Timestamp when the message was broadcasted.
	Created time.Time `protobuf:"bytes,4,opt,name=created,proto3,stdtime" json:"created"`
	// Seconds after created time until the message expires. This requires
	// roughly synced times between peers
	TTLSeconds uint64 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
}

func (m *BroadcastMessage) Reset()         { *m = BroadcastMessage{} }
func (m *BroadcastMessage) String() string { return proto.CompactTextString(m) }
func (*BroadcastMessage) ProtoMessage()    {}
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8266a42107f80093, []int{0}
}
func (m *BroadcastMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BroadcastMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BroadcastMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BroadcastMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastMessage.Merge(m, src)
}
func (m *BroadcastMessage) XXX_Size() int {
	return m.Size()
}
func (m *BroadcastMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastMessage proto.InternalMessageInfo

func (m *BroadcastMessage) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *BroadcastMessage) GetCreated() time.Time {
	if m != nil {
		return m.Created
	}
	return time.Time{}
}

func (m *BroadcastMessage) GetTTLSeconds() uint64 {
	if m != nil {
		return m.TTLSeconds
	}
	return 0
}

type HelloRequest struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8266a42107f80093, []int{1}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return m.Size()
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*BroadcastMessage)(nil), "relayer.v1beta1.BroadcastMessage")
	proto.RegisterType((*HelloRequest)(nil), "relayer.v1beta1.HelloRequest")
}

func init() {
	proto.RegisterFile("relayer/v1beta1/broadcast_message.proto", fileDescriptor_8266a42107f80093)
}

var fileDescriptor_8266a42107f80093 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0xb2, 0xb1, 0x32, 0x0f, 0x41, 0x15, 0x4d, 0x28, 0xf4, 0x90, 0x54, 0xbd, 0x10, 0x21,
	0x35, 0xd6, 0xc6, 0x1d, 0x41, 0xd4, 0xc3, 0x2a, 0x81, 0x84, 0x42, 0x4f, 0xbb, 0x54, 0x4e, 0xfc,
	0x08, 0x16, 0x6e, 0x1c, 0x6c, 0x77, 0x52, 0xfe, 0xc5, 0x7e, 0xd6, 0x8e, 0x3b, 0xa2, 0x1d, 0x02,
	0x4a, 0x0f, 0xfc, 0x0d, 0x94, 0x38, 0x96, 0x0a, 0xbb, 0x7d, 0xef, 0xbd, 0xef, 0x7d, 0x9f, 0xbe,
	0x67, 0xa3, 0xd7, 0x12, 0x38, 0xa9, 0x41, 0xe2, 0x9b, 0x8b, 0x0c, 0x34, 0xb9, 0xc0, 0x99, 0x14,
	0x84, 0xe6, 0x44, 0xe9, 0xcd, 0x16, 0x94, 0x22, 0x05, 0xc4, 0x95, 0x14, 0x5a, 0x78, 0x2f, 0x06,
	0x62, 0x3c, 0x10, 0xa7, 0xe7, 0x85, 0x28, 0x44, 0x3f, 0xc3, 0x1d, 0x32, 0xb4, 0xe9, 0xab, 0x42,
	0x88, 0x82, 0x03, 0xee, 0xab, 0x6c, 0xf7, 0x15, 0x93, 0xb2, 0x1e, 0x46, 0xe1, 0xff, 0x23, 0xcd,
	0xb6, 0xa0, 0x34, 0xd9, 0x56, 0x86, 0x30, 0xff, 0xe3, 0xa2, 0x49, 0x62, 0xed, 0x3f, 0x19, 0x77,
	0xef, 0x25, 0x72, 0x19, 0xf5, 0x9d, 0x99, 0x13, 0x9d, 0x26, 0x27, 0x6d, 0x13, 0xba, 0xab, 0x65,
	0xea, 0x32, 0xea, 0x95, 0xc8, 0x93, 0x90, 0xb3, 0x8a, 0x41, 0xa9, 0x37, 0x15, 0x80, 0xdc, 0x30,
	0xaa, 0x7c, 0x77, 0x76, 0x14, 0x9d, 0x26, 0xef, 0x1f, 0x9a, 0x30, 0x2a, 0x98, 0xfe, 0xb6, 0xcb,
	0xe2, 0x5c, 0x6c, 0x31, 0x67, 0x59, 0x75, 0x59, 0xe1, 0x42, 0x2c, 0x0c, 0x5a, 0xe4, 0x42, 0x02,
	0xee, 0x96, 0xe2, 0xd5, 0xb2, 0x6d, 0xc2, 0x49, 0x6a, 0x95, 0x3e, 0x03, 0xc8, 0xd5, 0x52, 0xa5,
	0x13, 0xf9, 0x4f, 0x87, 0x2a, 0xef, 0x1a, 0x8d, 0x2b, 0x52, 0x73, 0x41, 0xa8, 0x7f, 0x34, 0x73,
	0xa2, 0xb3, 0xcb, 0xf3, 0xd8, 0xe4, 0x89, 0x6d, 0x9e, 0xf8, 0x43, 0x59, 0x27, 0x6f, 0xee, 0x9a,
	0x70, 0xf4, 0xd0, 0x84, 0xf3, 0x03, 0xfb, 0xee, 0x3c, 0x07, 0xa9, 0xeb, 0x0a, 0x54, 0xc7, 0x4d,
	0xad, 0xa0, 0xf7, 0x0e, 0x8d, 0x73, 0x09, 0x44, 0x03, 0xf5, 0x8f, 0x7b, 0xed, 0xe9, 0x23, 0xed,
	0xb5, 0xbd, 0x55, 0xf2, 0xb4, 0x73, 0xb8, 0xfd, 0x15, 0x3a, 0xa9, 0x5d, 0xf2, 0x30, 0x3a, 0xd3,
	0x9a, 0x6f, 0x14, 0xe4, 0xa2, 0xa4, 0xca, 0x7f, 0x32, 0x73, 0xa2, 0xe3, 0xe4, 0x79, 0xdb, 0x84,
	0x68, 0xbd, 0xfe, 0xf8, 0xc5, 0x74, 0x53, 0xa4, 0x35, 0x1f, 0xf0, 0x3c, 0x42, 0xcf, 0xae, 0x80,
	0x73, 0x91, 0xc2, 0x8f, 0x1d, 0x28, 0xed, 0xf9, 0x68, 0x3c, 0xbc, 0xb6, 0xb9, 0x74, 0x6a, 0xcb,
	0xe4, 0xea, 0xae, 0x0d, 0x9c, 0xfb, 0x36, 0x70, 0x7e, 0xb7, 0x81, 0x73, 0xbb, 0x0f, 0x46, 0xf7,
	0xfb, 0x60, 0xf4, 0x73, 0x1f, 0x8c, 0xae, 0xe3, 0x83, 0x84, 0xdf, 0xc9, 0x0d, 0x59, 0x70, 0x92,
	0x29, 0x83, 0x32, 0xc9, 0x68, 0x01, 0xd8, 0x7e, 0xad, 0x3e, 0x71, 0x76, 0xd2, 0x67, 0x79, 0xfb,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xca, 0x4f, 0x57, 0xd7, 0x72, 0x02, 0x00, 0x00,
}

func (m *BroadcastMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BroadcastMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BroadcastMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TTLSeconds != 0 {
		i = encodeVarintBroadcastMessage(dAtA, i, uint64(m.TTLSeconds))
		i--
		dAtA[i] = 0x28
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Created, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Created):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintBroadcastMessage(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	{
		size := m.Payload.Size()
		i -= size
		if _, err := m.Payload.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBroadcastMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.RecipientPeerIDs) > 0 {
		for iNdEx := len(m.RecipientPeerIDs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.RecipientPeerIDs[iNdEx].Size()
				i -= size
				if _, err := m.RecipientPeerIDs[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintBroadcastMessage(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintBroadcastMessage(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HelloRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HelloRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HelloRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintBroadcastMessage(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBroadcastMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovBroadcastMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BroadcastMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovBroadcastMessage(uint64(l))
	}
	if len(m.RecipientPeerIDs) > 0 {
		for _, e := range m.RecipientPeerIDs {
			l = e.Size()
			n += 1 + l + sovBroadcastMessage(uint64(l))
		}
	}
	l = m.Payload.Size()
	n += 1 + l + sovBroadcastMessage(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Created)
	n += 1 + l + sovBroadcastMessage(uint64(l))
	if m.TTLSeconds != 0 {
		n += 1 + sovBroadcastMessage(uint64(m.TTLSeconds))
	}
	return n
}

func (m *HelloRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovBroadcastMessage(uint64(l))
	}
	return n
}

func sovBroadcastMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBroadcastMessage(x uint64) (n int) {
	return sovBroadcastMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BroadcastMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBroadcastMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BroadcastMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BroadcastMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroadcastMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientPeerIDs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroadcastMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_libp2p_go_libp2p_core_peer.ID
			m.RecipientPeerIDs = append(m.RecipientPeerIDs, v)
			if err := m.RecipientPeerIDs[len(m.RecipientPeerIDs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroadcastMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Payload.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroadcastMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Created, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TTLSeconds", wireType)
			}
			m.TTLSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroadcastMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TTLSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBroadcastMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HelloRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBroadcastMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HelloRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HelloRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroadcastMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBroadcastMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBroadcastMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBroadcastMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBroadcastMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBroadcastMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBroadcastMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBroadcastMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBroadcastMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBroadcastMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBroadcastMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBroadcastMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBroadcastMessage = fmt.Errorf("proto: unexpected end of group")
)
