name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  contract-test:
    name: Test Contracts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contract
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: contract/package-lock.json
      - run: npm ci
      - run: npm test
  contract-lint:
    name: Lint Contracts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contract
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: contract/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier
      - run: npm run solhint
  relayer:
    name: Test Relayer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: make build
      - run: make vet
      - run: make test
  relayer-lint:
    name: Lint Relayer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout 5m
